server:
  port: ${serverPort}

spring:
  application:
    name: ${artifactId}
  profiles:
    active: dev

eureka:
  client:
    instance-info-replication-interval-seconds: 15
    initial-instance-info-replication-interval-seconds: 20
    register-with-eureka: true
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

giants:
  boot:
    base-package: ${package}
    call-stack-time-analyse-log-config:
      http-request-exe-time-threshold: 500
    db-transaction:
      required-tx-methods:
        - create*
        - update*
        - delete*
        - move*
        - disable*
        - enable*