eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: ${eurekaServiceUrl}

spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/demo?useSSL=false&characterEncoding=utf8&autoReconnect=true
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 111111
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 6000
      minEvictableIdleTimeMillis: 30000
      validationQuery: select 'x'
      testWhileIdle:  true
      testOnBorrow: true
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 2000

logging:
  level:
    com: warn